RelatoriosProtheus/Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RelatoriosProtheus.Data;
using RelatoriosProtheus.Models.Entities;
using RelatoriosProtheus.Models.ViewModels;
using RelatoriosProtheus.Utils;
using System.Security.Claims;
using Microsoft.IdentityModel.Tokens;
using Microsoft.EntityFrameworkCore;
using AspNetCoreHero.ToastNotification.Abstractions;
using FluentEmail.Core;
using System;
using System.Linq;

namespace RelatoriosProtheus.Controllers
{
    [Authorize]
    public class AuthController : Controller
    {
        private readonly ILogger<AuthController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly INotyfService _toast;
        private readonly IFluentEmail _mail;

        public AuthController(ILogger<AuthController> logger, ApplicationDbContext context, INotyfService toast, IFluentEmail mail)
        {
            _logger = logger;
            _context = context;
            _toast = toast;
            _mail = mail;
        }

        public IActionResult Index()
        {
            var usuarios = _context.Funcionarios
                .ToList();

            List<UsuarioViewModel> usuariosPerfis = new List<UsuarioViewModel>();

            foreach (var item in usuarios)
            {
                var perfisUsuario = _context.Perfis_Funcionarios
                    .Include(pf => pf.PerfilFk)
                    .Where(pf => pf.FuncionarioId == item.Id)
                    .Select(pf => pf.PerfilFk.Descricao);

                usuariosPerfis.Add(new UsuarioViewModel
                {
                    Matricula = item.Matricula,
                    FuncionarioId = item.Id,
                    Email = item.Email,
                    Perfis = perfisUsuario
                });
            }

            ViewBag.Perfis = _context.Perfis
                .Where(p => p.Descricao != "Administrador")
                .ToList();

            var perfis = _context.Perfis.ToList();
            return View(usuariosPerfis);
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Login(string returnUrl = null)
        {
            var vm = new LoginViewModel
            {
                ReturnUrl = returnUrl
            };
            return View(vm);
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public IActionResult Login([Bind("Empresa,Matricula,Senha")] LoginViewModel login)
        {
            if (!ModelState.IsValid)
            {
                return View(login);
            }

            try
            {
                var empresaEnum = EnumsUtils.retornarEnum(login.Empresa);

                var funcionario = _context.Funcionarios
                    .Include(f => f.Perfis)
                    .ThenInclude(pf => pf.PerfilFk)
                    .FirstOrDefault(f =>
                        f.Empresa == empresaEnum &&
                        f.Matricula == login.Matricula &&
                        f.Senha == login.Senha);

                if (funcionario == null)
                {
                    ModelState.AddModelError(string.Empty, "Usuário não encontrado, por favor tente novamente.");
                    return View(login);
                }

                AutenticarIdentity(funcionario, login.RememberMe);

                if (!string.IsNullOrWhiteSpace(login.ReturnUrl))
                    return LocalRedirect(login.ReturnUrl);

                return RedirectToAction("Index", "Relatorios");
            }
            catch (Exception)
            {
                ModelState.AddModelError(string.Empty, "Ocorreu um erro ao processar o login.");
                return View(login);
            }
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return Redirect("Login");
        }

        [AllowAnonymous]
        public IActionResult RecuperarSenha()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RecuperarSenha([Bind("Email")]EsqueceuSenhaViewModel vw)
        {
            if (ModelState.IsValid)
            {
                var func = _context.Funcionarios
                    .Where(f => f.Email == vw.Email && f.Situacao != 0)
                    .FirstOrDefault();

                if (func != null)
                {
                    var model = new EsqueceuSenhaViewModel
                    {
                        Nome = func.Nome,
                        Email = func.Email,
                        Matricula = func.Matricula,
                        Senha = func.Senha
                    };
                    await EnviarEmail(model);
                }
                else
                {
                    _toast.Error("E-mail não identificado.");
                }
            }
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View("Create");
        }


        [HttpPost]
        public IActionResult Create(Funcionarios funcionario)
        {
            if (_context.Funcionarios.Any((f => f.Matricula == funcionario.Matricula && f.Empresa == funcionario.Empresa)))
            {
                _toast.Error("Já existe um usuário cadastrado com essa matrícula.");
                return View(funcionario);
            }

            funcionario.Situacao = 1;

            _context.Funcionarios.Add(funcionario);
            _context.SaveChanges();

            return RedirectToAction("Index", "Relatorios");
        }

        public IActionResult Edit(int id)
        {
            var usuario = _context.Funcionarios.Find(id);
            var func = new FuncionarioEditViewModel()
            {
                Email = usuario.Email,
                Empresa = usuario.Empresa,
                Id = usuario.Id,
                Matricula = usuario.Matricula,
                Nome = usuario.Nome,
                Senha = usuario.Senha,
                Situacao = usuario.Situacao == 1 ? true : false
            };
            return View(func);
        }

        [HttpPost]
        public IActionResult Edit(Funcionarios usuario)
        {
            var usuarioDb = _context.Funcionarios.FirstOrDefault(u => u.Id == usuario.Id);
            if (usuarioDb != null)
            {
                usuarioDb.Matricula = usuario.Matricula;
                usuarioDb.Nome = usuario.Nome;
                usuarioDb.Email = usuario.Email;
                usuarioDb.Senha = usuario.Senha;
                usuarioDb.Situacao = usuario.Situacao;
                usuarioDb.Empresa = usuario.Empresa;
                _context.Funcionarios.Update(usuarioDb);
                _context.SaveChanges();
            }
            return RedirectToAction("Index", "Relatorios");
        }

        public async Task<IActionResult> Perfis(int Id)
        {
            var idClaim = Convert.ToInt32(User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var userClaim = _context.Funcionarios.Where(x => x.Id == idClaim).Include(pf => pf.Perfis).ThenInclude(y => y.PerfilFk).FirstOrDefault();
            
            var usuario = await _context.Funcionarios.FindAsync(Id);

            var perfisUsuario = _context.Perfis_Funcionarios
                .Include(pf => pf.PerfilFk)
                .Where(pf => pf.FuncionarioId == Id && pf.PerfilId != 0)
                .Select(pf => pf.PerfilFk.Descricao)
                .ToList();

            var isAdm = userClaim.Perfis.Select(pf => pf.PerfilFk.Descricao).Contains("Administrador");

            var todosPerfis = _context.Perfis
                .Select(p => p.Descricao)
                .ToList();

            var disponiveis = todosPerfis.Except(perfisUsuario);

            if (!isAdm)
            {
                disponiveis = disponiveis.Where(p => p != "Administrador");
            }

            var usuarioPerfis = new UsuarioViewModel
            {
                Matricula = usuario.Matricula,
                FuncionarioId = usuario.Id,
                Email = usuario.Email,
                Perfis = perfisUsuario.AsQueryable()
            };

            ViewBag.Perfis = disponiveis.ToList();

            return View(usuarioPerfis);
        }

        [HttpPost]
        public async Task<bool> Perfil(int funcionarioId, string[] perfisUsuario)
        {
            try
            {
                var listaPerfisFuncionario = _context.Perfis_Funcionarios
                .Where(pf => pf.FuncionarioId == funcionarioId && pf.PerfilId != 1)
                .ToList();

                _context.Perfis_Funcionarios.RemoveRange(listaPerfisFuncionario);
                await _context.SaveChangesAsync();

                var perfis = _context.Perfis.ToList();

                for (int i = 0; i < perfisUsuario.Length; i++)
                {
                    var perfilId = perfis
                        .Where(p => p.Descricao == perfisUsuario[i])
                        .Select(p => p.Id)
                        .First();

                    Perfis_Funcionarios perfisFuncionarios = new Perfis_Funcionarios
                    {
                        FuncionarioId = funcionarioId,
                        PerfilId = perfilId,
                    };

                    _context.Perfis_Funcionarios.Add(perfisFuncionarios);
                    await _context.SaveChangesAsync();
                }
                return true;
            }
            catch (Exception)
            {
                return false;
            }
        }

        [HttpPost]
        public async Task<IActionResult> ChangePerfilUsuario(int FuncionarioId, string Perfil, bool active)
        {
            var usuario = await _context.Funcionarios.FindAsync(FuncionarioId);

RelatoriosProtheus/Controllers/PerfilsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RelatoriosProtheus.Data;
using RelatoriosProtheus.Models.Entities;
using RelatoriosProtheus.Models.ViewModels;

namespace RelatoriosProtheus.Controllers
{
    public class PerfilsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PerfilsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Perfils
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Perfis.ToListAsync());
        }

        // GET: Perfils/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var perfil = await _context.Perfis
                .FirstOrDefaultAsync(m => m.Id == id);
            if (perfil == null)
            {
                return NotFound();
            }

            return View(perfil);
        }

        // GET: Perfils/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Perfils/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Descricao")] PerfilCreateViewModel perfilVm)
        {
            if (!ModelState.IsValid)
                return View(perfilVm);

            var perfil = new Perfil
            {
                Descricao = perfilVm.Descricao
            };
            _context.Add(perfil);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Perfils/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var perfil = await _context.Perfis.FindAsync(id);
            if (perfil == null)
                return NotFound();

            var perfilVm = new PerfilEditViewModel()
            {
                Id = perfil.Id,
                Descricao = perfil.Descricao
            };
            return View(perfilVm);
        }

        // POST: Perfils/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, PerfilEditViewModel vm)
        {
            if (id != vm.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
                return View(vm);

            try
            {
                var perfil = new Perfil
                {
                    Id = vm.Id,
                    Descricao = vm.Descricao
                };

                _context.Update(perfil);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PerfilExists(vm.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Perfils/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var perfil = await _context.Perfis
                .FirstOrDefaultAsync(m => m.Id == id);
            if (perfil == null)
            {
                return NotFound();
            }

            return View(perfil);
        }

        // POST: Perfils/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var perfil = await _context.Perfis.FindAsync(id);
            if (perfil != null)
            {
                _context.Perfis.Remove(perfil);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PerfilExists(int id)
        {
            return _context.Perfis.Any(e => e.Id == id);
        }
    }
}

RelatoriosProtheus/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@{
    var claims = string.Join(",", ((ClaimsIdentity)User.Identity).Claims.ToList());
}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>@ViewData["Title"] - RelatoriosProtheus</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.14.0/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.2/css/dataTables.dataTables.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RelatoriosProtheus.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" asp-append-version="true" />
</head>
<body class="d-flex flex-column min-vh-100" style="font-family: 'Poppins', sans-serif;">
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand d-flex align-items-center" href="@Url.Action("Index", "Relatorios")">
                    <div style="display: inline-grid">
                        <img src="~/img/SESI_SENAI.png" alt="SESI/SENAI" height="40" width="200px" />
                        <span class="fw-bold">Relatórios Protheus</span>
                    </div>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNavbar" aria-controls="mainNavbar" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="mainNavbar">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (claims.Contains("Administrador") || claims.Contains("Gestor"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Grupos" asp-action="Index">
                                        <i class="bi bi-collection me-1"></i> Grupos
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Perfils" asp-action="Index">
                                        <i class="bi bi-layout-text-sidebar me-1"></i> Perfis
                                    </a>
                                </li>                                
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Auth" asp-action="Index">
                                        <i class="bi bi-people me-1"></i> Usuarios
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Relatorios" asp-action="RelatoriosGrupos">
                                        <i class="bi bi-archive me-1"></i> Relatórios
                                    </a>
                                </li>
                            }
                        }
                    </ul>

                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0 align-items-center">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle d-flex align-items-center" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="bi bi-person-circle fs-4 me-1"></i>
                                    <span>@User.Identity.Name</span>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                                    <li>
                                        <a class="dropdown-item" asp-controller="Auth" asp-action="Edit" asp-route-id="@User.FindFirst(ClaimTypes.NameIdentifier).Value">Editar</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><form asp-controller="Auth" asp-action="Logout" method="post" class="m-0">
                                        <button type="submit" class="dropdown-item text-danger">
                                            <i class="bi bi-box-arrow-right me-1"></i> Sair
                                        </button>
                                    </form></li>
                                </ul>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Auth" asp-action="Index">
                                    <i class="bi bi-box-arrow-in-right me-1"></i> Login
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
        <div style="height: 70px;"></div>
    </header>

    <main class="container flex-fill py-4 mt-5">
        @RenderBody()
    </main>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-ui-1.14.0/jquery-ui.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="https://cdn.datatables.net/2.0.2/js/dataTables.min.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.1/js/dataTables.buttons.min.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await Component.InvokeAsync("Notyf")
</body>
</html>